version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - backend

  flask:
    build: .
    container_name: flask-app
    ports:
      - "5002:5000"
    command: python3 lib/main.py
    volumes:
      - ./output:/app/output
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend

  # docker-compose --profile csv up OR docker-compose csv_generator
  csv_generator:
    build: .
    container_name: csv_generator
    volumes:
      - ./output:/app/output
    profiles:
      - csv
    command: >
      python lib/generate_hospitals_csv.py

  # docker-compose --profile csv up OR docker-compose csv_loader
  csv_loader:
    build: .
    container_name: csv_loader
    volumes:
      - ./output:/app/output
    depends_on:
      redis:
        condition: service_healthy
    command: >
      python lib/csv_to_redis_loader.py
    profiles:
      - csv
    networks:
      - backend

  test:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pytest"

networks:
  backend:
    driver: bridge
